/*NAVIGATION MENU*/
document.addEventListener('DOMContentLoaded', () => {
    const menuToggle = document.querySelector('.menu-toggle');
    const navMenu = document.querySelector('.nav-menu');
    const body = document.body;

    // Toggle Menu
    menuToggle.addEventListener('click', (e) => {
        e.stopPropagation();
        navMenu.classList.toggle('open');
        body.classList.toggle('menu-pushed');
    });

    // Close menu when clicking anywhere else
    document.addEventListener('click', (e) => {
        if (!navMenu.contains(e.target) && navMenu.classList.contains('open')) {
            navMenu.classList.remove('open');
            body.classList.remove('menu-pushed');
        }
    });
});

// =========================================
// USER PROFILE: ADD COMMITTEE MODAL
// =========================================
document.addEventListener('DOMContentLoaded', () => {
    const committeeModal = document.getElementById('addCommitteeModal');
    const addCommitteeBtn = document.querySelector('.add-committee-btn');
    const committeeCloseBtns = document.querySelectorAll('#addCommitteeModal .close-modal');

    // Only attach event listeners if the Add Committee button exists on this page
    if (addCommitteeBtn && committeeModal) {

        // Open Modal
        addCommitteeBtn.onclick = (e) => {
            e.preventDefault();
            committeeModal.style.display = 'flex';
        };

        // Close Modal 
        committeeCloseBtns.forEach(btn => {
            btn.onclick = (e) => {
                e.preventDefault();
                committeeModal.style.display = 'none';
            };
        });

        // Close on outside click
        window.addEventListener('click', (e) => {
            if (e.target === committeeModal) {
                committeeModal.style.display = 'none';
            }
        });
    }
});

// =========================================
// USER MANAGEMENT: ADD OFFICER MODAL
// =========================================
document.addEventListener('DOMContentLoaded', () => {
    // Modals/Forms
    const officerModal = document.getElementById('officerModal');
    const deleteModal = document.getElementById('deleteModal');
    const form = document.getElementById('officerForm');
    const modalTitle = document.getElementById('modalTitle');
    const deleteName = document.getElementById('targetName');
    const filterWrapper = document.querySelector('.filter-wrapper');
    const filterYear = document.getElementById('filterYear');
    const customRange = document.getElementById('customYearRange');
    const yearFrom = document.getElementById('yearFrom');
    const yearTo = document.getElementById('yearTo');

    // Buttons
    const addOfficerBtn = document.querySelector('.new-officer-btn');
    const officerCloseBtns = document.querySelectorAll('#officerModal .close-modal');
    const uploadBtn = document.querySelector('.btn-upload'); // Add/Edit button
    const confirmBtn = document.querySelector('.btn-confirm'); // Delete button
    const allCloseBtn = document.querySelectorAll('.close-modal');
    const sortBtn = document.querySelector('.sort-btn');
    const filterBtn = document.getElementById('filterBtn');

    // Table
    const tbody = document.getElementById('tBody');
    const editRow = document.getElementById('editRow');
    const searchInput = document.querySelector('.users-header-controls .search-input');

    // Initialize existing rows generated by PHP
    if (tbody) {
        const existingRows = tbody.querySelectorAll('tr:not(.empty-row)');
        existingRows.forEach(row => {
            const rowId = row.getAttribute('data-id');
            if (rowId) {
                showActionButtons(row, rowId);
            }
        });
    }

    // Initialize for Dropdown
    let currentOpenDropdown = null;

    // Initialize for Delete Modal
    let currentDelete = null;

    // --- METHODS ---
    // Open Modal 
    function openModal() { officerModal.style.display = 'flex'; }

    // Multi-functional Close Modal
    function closeModal() {
        officerModal.style.display = 'none';
        deleteModal.style.display = 'none';
        form.reset();
        editRow.value = "";
        modalTitle.textContent = "Add New Officer";
        uploadBtn.textContent = "Add Officer";
    }

    // Open Delete Modal
    function showDeleteModal(row, name) {
        currentDelete = row;
        deleteName.textContent = name;
        deleteModal.style.display = 'flex';
    }

    // Open Edit Modal
    function openEditModal(row, rowId) {
        const data = JSON.parse(row.getAttribute('data-info'));

        document.getElementById('officerFullName').value = data.fullName;
        document.getElementById('officerStudentId').value = data.studentId;
        document.getElementById('officerAge').value = data.age;
        document.getElementById('officerContact').value = data.contact;
        document.getElementById('officerCourse').value = data.course;
        document.getElementById('officerYearLevel').value = data.yearLevel;
        document.getElementById('officerPosition').value = data.position;
        document.getElementById('officerTermYear').value = data.termYear;
        document.getElementById('officerDateAssumed').value = data.dateAssumed;
        document.getElementById('officerAccessLevel').value = data.accessLevel;

        editRow.value = rowId;
        modalTitle.textContent = "Edit Officer";
        uploadBtn.textContent = "Update Officer";
        openModal();
    }

    // Update "No Entries Yet!" Row Placeholder
    function updateEmptyPlaceholder() {
        const rows = tbody.querySelectorAll('tr');
        const emptyRow = tbody.querySelector('.empty-row');

        if (rows.length > 0 && emptyRow) {
            emptyRow.remove();
        } else if (rows.length === 0 && !emptyRow) {
            tbody.innerHTML = `<tr class="empty-row" id="emptyRow">
                <td colspan="5" style="color: #c872b5; text-align: center;"> <strong> NO ENTRIES YET! </strong></td>
            </tr>`;
        }
    }

    // Validate and get data (e.g., name, term year, roles)
    function getData() {
        const fullName = document.getElementById('officerFullName').value;
        const studentId = document.getElementById('officerStudentId').value;
        const age = document.getElementById('officerAge').value;
        const contact = document.getElementById('officerContact').value;
        const course = document.getElementById('officerCourse').value;
        const yearLevel = document.getElementById('officerYearLevel').value;
        const position = document.getElementById('officerPosition').value;
        const termYear = document.getElementById('officerTermYear').value;
        const dateAssumed = document.getElementById('officerDateAssumed').value;
        const accessLevel = document.getElementById('officerAccessLevel').value;

        return {
            fullName,
            studentId,
            age,
            contact,
            course,
            yearLevel,
            position,
            termYear,
            dateAssumed,
            accessLevel,
        };
    }

    // New row from data
    function createRow(data, rowId = null) {
        const id = rowId || Date.now();
        const row = document.createElement('tr');

        // For Status
        const statusClass = data.status === 'active' ? 'status-active' : 'status-inactive';
        const statusText = data.status === 'active' ? 'Active' : 'Inactive';
        row.setAttribute('data-id', id);
        row.setAttribute('data-info', JSON.stringify(data));

        const initial = data.fullName ? escapeHTML(data.fullName.charAt(0)) : '?';

        row.innerHTML = `
            <td>
                <div style="display: flex; align-items: center; gap: 10px;">
                    <div style="width: 32px; height: 32px; border-radius: 50%; background: #4b2c6e; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold;">
                        ${initial}
                    </div>
                    ${escapeHTML(data.fullName)}
                </div>
            </td>
            <td>${escapeHTML(data.termYear || 'N/A')}</td>
            <td>${escapeHTML(data.position || 'N/A')}</td>
            <td data-label="Status"><span class="status-badge ${statusClass}">${statusText}</span></td> 
        `;

        showActionButtons(row, id);
        return row;
    }

    // Add row to table
    function addRow(data, id) {
        const dataWithStatus = { ...data, status: 'active' };

        const newRow = createRow(dataWithStatus, id);
        tbody.prepend(newRow); // show at the top
        updateEmptyPlaceholder();
    }

    // Update exisiting row
    function updateRow(rowId, data) {
        const row = tbody.querySelector(`tr[data-id="${rowId}"]`);
        if (row) {
            const existingData = JSON.parse(row.getAttribute('data-info') || '{}');
            const initial = data.fullName ? escapeHTML(data.fullName.charAt(0)) : '?';

            row.cells[0].innerHTML = `
                <div style="display: flex; align-items: center; gap: 10px;">
                    <div style="width: 32px; height: 32px; border-radius: 50%; background: #4b2c6e; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold;">
                        ${initial}
                    </div>
                    ${escapeHTML(data.fullName)}
                </div>
            `;
            row.cells[1].textContent = data.termYear || 'N/A';
            row.cells[2].textContent = data.position || 'N/A';

            const updatedData = { ...data, status: existingData.status || 'active' };
            row.setAttribute('data-info', JSON.stringify(updatedData));
        }
    }

    // Delete Row
    function deleteRow(row) {
        if (row) {
            row.remove();
            updateEmptyPlaceholder();
        }
        closeModal();
    }

    function escapeHTML(str) {
        const m = document.createElement('m');
        m.textContent = str;
        return m.innerHTML;
    }

    // Show Options in Dropdown
    function showActionButtons(row, rowId) {
        const actionCell = document.createElement('td');
        actionCell.className = "action-cell";

        const menuDiv = document.createElement('div');
        menuDiv.className = 'actions-menu';

        const triDotsBtn = document.createElement('button');
        triDotsBtn.className = 'dots-btn';
        triDotsBtn.textContent = '•••';

        const dropdown = document.createElement('div');
        dropdown.className = 'dropdown-action';

        const editBtn = document.createElement('button');
        editBtn.type = "button";
        editBtn.textContent = "Edit Officer";
        editBtn.className = 'edit-btn';
        editBtn.onclick = (e) => {
            e.stopPropagation();
            openEditModal(row, rowId);
            menuDiv.classList.remove('active');
            menuDiv.classList.remove('dropup')
            if (currentOpenDropdown === menuDiv) {
                currentOpenDropdown = null;
            }
        };

        const deleteBtn = document.createElement('button');
        deleteBtn.type = "button";
        deleteBtn.textContent = "Delete Officer";
        deleteBtn.className = 'delete-btn';
        deleteBtn.onclick = (e) => {
            e.stopPropagation();
            const name = JSON.parse(row.getAttribute('data-info')).fullName;
            showDeleteModal(row, name);
            menuDiv.classList.remove('active');
            menuDiv.classList.remove('dropup');
            if (currentOpenDropdown === menuDiv) {
                currentOpenDropdown = null;
            }
        }

        dropdown.appendChild(editBtn);
        dropdown.appendChild(deleteBtn);
        menuDiv.appendChild(triDotsBtn);
        menuDiv.appendChild(dropdown);
        actionCell.appendChild(menuDiv);

        // Ensure action cell exists in the right place
        const oldActionCell = row.querySelector('.action-cell, .actions-cell, td:last-child');
        if (oldActionCell && !oldActionCell.classList.contains('action-cell')) {
            row.replaceChild(actionCell, oldActionCell);
        } else if (!oldActionCell) {
            row.appendChild(actionCell);
        }

        function adjustDropdown(menuDiv) {
            const dropdownMenu = menuDiv.querySelector('.dropdown-action');

            dropdownMenu.style.display = 'block';
            dropdownMenu.style.visibility = 'hidden';

            const menuRect = dropdownMenu.getBoundingClientRect();
            const btnRect = menuDiv.getBoundingClientRect();

            const spaceBelow = window.innerHeight - btnRect.bottom;
            const buffer = 20;

            if (spaceBelow < menuRect.height + buffer) {
                menuDiv.classList.add('dropup');
            } else {
                menuDiv.classList.remove('dropup');
            }

            dropdownMenu.style.display = '';
            dropdownMenu.style.visibility = '';
        }

        // Dropdown Action
        triDotsBtn.addEventListener('click', (e) => {
            e.stopPropagation();

            // Close Sort & Filter if opened
            if (filterWrapper) {
                filterWrapper.classList.remove('active');
            }

            // Close other dropdowns if open
            if (currentOpenDropdown && currentOpenDropdown !== menuDiv) {
                currentOpenDropdown.classList.remove('active');
                currentOpenDropdown.classList.remove('dropup');
            }

            // Toggle current dropdown
            if (menuDiv.classList.contains('active')) {
                menuDiv.classList.remove('active');
                menuDiv.classList.remove('dropup');
                currentOpenDropdown = null;
            } else {
                adjustDropdown(menuDiv);
                menuDiv.classList.add('active');
                currentOpenDropdown = menuDiv;
            }
        });
    }

    function applyFilterAndSort() {
        const filterRole = document.getElementById('filterRole').value;
        const filterStatus = document.getElementById('filterStatus').value;
        const filterYear = document.getElementById('filterYear').value;
        const sortType = document.getElementById('sortType').value;
        const sortOrder = document.getElementById('sortOrder').value;
        const searchTerm = searchInput ? searchInput.value.toLowerCase() : "";

        // Get all rows
        let rows = Array.from(tbody.querySelectorAll('tr:not(.empty-row)'));

        // Only show visible rows
        let visibleRows = [];

        rows.forEach(row => {
            // Reset row first
            row.style.display = '';

            const data = JSON.parse(row.getAttribute('data-info'));
            const statusSpan = row.querySelector('td:nth-child(4) span');
            const status = statusSpan ? statusSpan.textContent.toLowerCase() : '';

            // Filter Logic
            let showRow = true;

            // Search Filter
            if (searchTerm && !(data.fullName.toLowerCase().includes(searchTerm) || (data.studentId && data.studentId.toLowerCase().includes(searchTerm)))) {
                showRow = false;
            }

            // Role Filter
            if (filterRole !== "allRoles" && data.position !== filterRole) { showRow = false; }

            // Status Filter 
            if (filterStatus !== "allStatus" && status !== filterStatus) { showRow = false; }

            // Year Filter
            if (filterYear !== "allTime") {
                const termYear = data.termYear.replace(/\s/g, ''); // Removes the spaces (e.g., 2025 - 2026 --> 2025-2026)
                if (filterYear === 'present' && termYear !== '2026-2027') { showRow = false; }
                if (filterYear === 'previous-year' && termYear !== '2025-2026') { showRow = false; }
                if (filterYear === 'last-previous-year' && termYear !== '2024-2025') { showRow = false; }
                if (filterYear === 'custom') {
                    const from = parseInt(yearFrom.value);
                    const to = parseInt(yearTo.value);
                    if (!isNaN(from) && !isNaN(to)) {
                        const termStart = parseInt(termYear.split('-')[0]);
                        if (termStart < from || termStart > to) { showRow = false; }
                    }
                }
            }

            row.style.display = showRow ? '' : 'none';
            if (showRow) { visibleRows.push(row); }
        });

        // Sort Logic 
        visibleRows.sort((a, b) => {
            const dataA = JSON.parse(a.getAttribute('data-info'));
            const dataB = JSON.parse(b.getAttribute('data-info'));

            let valA, valB;

            switch (sortType) {
                case 'name':
                    // In any case there are prefixes (e.g, Mr., Ms., Mrs., Prof., Dr., Engr.)
                    function removePrefix(fullName) {
                        const prefixes = ['Dr. ', 'Prof. ', 'Engr. ', 'Mr. ', 'Ms. ', 'Mrs. ']; // May be added if there are more
                        let nameWithNoPrefix = fullName;
                        for (let prefix of prefixes) {
                            if (fullName.startsWith(prefix)) {
                                nameWithNoPrefix = fullName.substring(prefix.length);
                                break;
                            }
                        }
                        return nameWithNoPrefix.toLowerCase();
                    }

                    valA = dataA.fullName.toLowerCase();
                    valB = dataB.fullName.toLowerCase();
                    break;
                case 'dateAssumed':
                    valA = new Date(dataA.dateAssumed);
                    valB = new Date(dataB.dateAssumed);
                    break;
                case 'yearLevel':
                    valA = parseInt(dataA.yearLevel);
                    valB = parseInt(dataB.yearLevel);
                    break;
                default:
                    valA = dataA.fullName;
                    valB = dataB.fullName;
            }

            if (valA < valB) { return sortOrder === 'asc' ? -1 : 1; }
            if (valA > valB) { return sortOrder === 'asc' ? 1 : -1; }
            return 0;
        });

        visibleRows.forEach(row => tbody.appendChild(row));
    }

    // --- EVENT LISTENERS --- 
    // Open Modal
    if (addOfficerBtn) {
        addOfficerBtn.addEventListener('click', openModal);
    }

    // Modal (Close when clicked outside)
    window.addEventListener('click', (e) => {
        if (e.target === officerModal || e.target === deleteModal) {
            closeModal();
        }
    });

    // Sort & Filter 
    if (sortBtn && filterWrapper) {
        sortBtn.addEventListener('click', function (e) {
            e.preventDefault();
            e.stopPropagation();

            // Close dropdown action if opened
            if (currentOpenDropdown) {
                currentOpenDropdown.classList.remove('active');
                currentOpenDropdown.classList.remove('dropup');
                currentOpenDropdown = null;
            }

            filterWrapper.classList.toggle('active');
        });
    }

    // If "Custom Year" is chosen as an option
    if (filterYear && customRange) {
        filterYear.addEventListener('change', function () {
            if (this.value === 'custom') {
                customRange.style.display = 'block';
            } else {
                customRange.style.display = 'none';
            }
        });
    }

    // Prevents negative inputs in custom year
    [yearFrom, yearTo].forEach(input => {
        if (input) {
            input.addEventListener('change', function () {
                if (this.value !== "" && parseInt(this.value) < 0) {
                    alert("Please enter a valid year.");
                    this.value = "";
                    this.classList.add('input-error');
                } else {
                    this.classList.remove('input-error');
                }
            })
        }
    })

    // Sort & Filter (Closed when clicked outside)
    document.addEventListener('click', function (e) {
        if (filterWrapper && !filterWrapper.contains(e.target) && filterWrapper.classList.contains('active')) {
            filterWrapper.classList.remove('active');
        }

        const isClickInMenu = e.target.closest('.actions-menu');
        if (isClickInMenu && currentOpenDropdown) {
            currentOpenDropdown.classList.remove('active');
            currentOpenDropdown.classList.remove('dropup');
            currentOpenDropdown = null;
        }
    });

    // Sort & Filter Form
    if (filterBtn) {
        filterBtn.addEventListener('click', () => {
            applyFilterAndSort();
            filterWrapper.classList.remove('active');
        });
    }

    // Search Input
    if (searchInput) {
        searchInput.addEventListener('input', () => {
            applyFilterAndSort();
        });
    }

    // Submit/Edit Form
    form.addEventListener('submit', (e) => {
        e.preventDefault();
        const data = getData();
        const editingId = editRow.value;

        if (editingId) {
            data.id = editingId;
            fetch('api/edit_officer.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            })
                .then(res => res.json())
                .then(result => {
                    if (result.success) {
                        updateRow(editingId, data);
                        closeModal();
                    } else {
                        alert("Error updating: " + result.message);
                    }
                })
                .catch(err => alert("Request failed: " + err));
        } else {
            fetch('api/add_officer.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data)
            })
                .then(res => res.json())
                .then(result => {
                    if (result.success) {
                        addRow(data, result.id);
                        closeModal();
                    } else {
                        alert("Error adding: " + result.message);
                    }
                })
                .catch(err => alert("Request failed: " + err));
        }
    });

    // Delete Form
    confirmBtn.addEventListener('click', () => {
        if (currentDelete) {
            const rowId = currentDelete.getAttribute('data-id');
            fetch('api/delete_officer.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ id: rowId })
            })
                .then(res => res.json())
                .then(result => {
                    if (result.success) {
                        currentDelete.remove();
                        updateEmptyPlaceholder();
                        closeModal();
                        currentDelete = null;
                    } else {
                        alert("Error deleting officer: " + result.message);
                    }
                })
                .catch(err => alert("Request failed: " + err));
        }
    });

    // Close/Cancel Button
    allCloseBtn.forEach(btn => {
        btn.addEventListener('click', closeModal);
    });

    // Action Dropdown (Close when clicked outside)
    document.addEventListener('click', function (e) {
        const isClickInMenu = e.target.closest('.actions-menu');

        if (!isClickInMenu && currentOpenDropdown) {
            currentOpenDropdown.classList.remove('active');
            currentOpenDropdown.classList.remove('dropup');
            currentOpenDropdown = null;
        }
    });

});

// =========================================
// ACTIVITY LOG: FILTER BY USER AND ACTION
// =========================================
document.addEventListener('DOMContentLoaded', () => {
    const tableBody = document.querySelector(".file-table tbody");
    const actionFilter = document.querySelector(".filter-by-action .row-select");

    // Only run if we are actually on the Activity Log page
    if (!tableBody || !actionFilter) return;

    const searchInput = document.querySelector(".search-input");
    const userFilter = document.querySelector(".filter-by-user .row-select");
    const rowsPerPageSelect = document.querySelector(" .display-controls .row-select");

    const allRows = Array.from(tableBody.querySelectorAll("tr"))

    let filteredRows = [...allRows];

    let currentPage = 1;

    function updateTable() {
        const searchTerm = searchInput ? searchInput.value.toLowerCase() : "";

        const selectedUser = userFilter ? userFilter.options[userFilter.selectedIndex].text : "All Users";

        const selectedAction = actionFilter ? actionFilter.options[actionFilter.selectedIndex].text : "All Actions";

        filteredRows = allRows.filter(row => {
            const rowText = row.innerText.toLowerCase();

            const userCell = row.querySelector("td[data-label='Account']");
            const actionCell = row.querySelector("td[data-label='Actions']");

            const userCellText = userCell ? userCell.innerText : "";
            const actionCellText = actionCell ? actionCell.innerText : "";

            const matchesSearch = rowText.includes(searchTerm);

            const matchesUser = selectedUser === "All Users" || userCellText.includes(selectedUser);

            const actionKeyword = selectedAction === "All Actions" ? "" : selectedAction.split(' ')[0];
            const matchesAction = selectedAction === "All Actions" || actionCellText.includes(actionKeyword);

            return matchesSearch && matchesUser && matchesAction;

        });

        tableBody.innerHTML = "";

        filteredRows.forEach(row => {
            tableBody.appendChild(row);
        });
    }

    if (searchInput) {
        searchInput.addEventListener("input", () => {
            currentPage = 1;
            updateTable();
        });
    }

    if (userFilter) {
        userFilter.addEventListener("change", () => {
            currentPage = 1;
            updateTable();
        });
    }

    if (actionFilter) {
        actionFilter.addEventListener("change", () => {
            currentPage = 1;
            updateTable();
        });
    }

    if (rowsPerPageSelect) {
        rowsPerPageSelect.addEventListener("change", (e) => {
            rowsPerPage = parseInt(e.target.value);
            currentPage = 1;
            updateTable();
        });
    }

    updateTable();
});